<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoanTypesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('loan_types')->upsert([
            [
                'name' => 'Personal Loan',
                'slug' => 'personal',
                'description' => 'Flexible loans for personal needs and emergencies',
                'min_amount' => 1000,
                'max_amount' => 50000,
                'interest_rate' => 8.5,
                'processing_fee' => 500,
                'min_tenure_months' => 1,
                'max_tenure_months' => 6,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Business Loan',
                'slug' => 'business',
                'description' => 'Grow your business with working capital',
                'min_amount' => 5000,
                'max_amount' => 200000,
                'interest_rate' => 12.0,
                'processing_fee' => 1000,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Education Loan',
                'slug' => 'education',
                'description' => 'Invest in your education and future',
                'min_amount' => 2000,
                'max_amount' => 100000,
                'interest_rate' => 7.5,
                'processing_fee' => 500,
                'min_tenure_months' => 6,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emergency Loan',
                'slug' => 'emergency',
                'description' => 'Quick funds for unexpected expenses',
                'min_amount' => 500,
                'max_amount' => 30000,
                'interest_rate' => 10.0,
                'processing_fee' => 300,
                'min_tenure_months' => 1,
                'max_tenure_months' => 3,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Home Improvement',
                'slug' => 'home_improvement',
                'description' => 'Renovate and upgrade your home',
                'min_amount' => 10000,
                'max_amount' => 150000,
                'interest_rate' => 9.0,
                'processing_fee' => 1000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 18,
                'requires_guarantor' => false,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agriculture Loan',
                'slug' => 'agriculture',
                'description' => 'Finance farm inputs, seeds, and equipment',
                'min_amount' => 2000,
                'max_amount' => 100000,
                'interest_rate' => 9.0,
                'processing_fee' => 500,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Asset Finance',
                'slug' => 'asset_finance',
                'description' => 'Acquire equipment, machinery, or tools on credit',
                'min_amount' => 20000,
                'max_amount' => 500000,
                'interest_rate' => 13.0,
                'processing_fee' => 2000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salary Advance',
                'slug' => 'salary_advance',
                'description' => 'Short-term advance against your next paycheck',
                'min_amount' => 500,
                'max_amount' => 20000,
                'interest_rate' => 6.0,
                'processing_fee' => 200,
                'min_tenure_months' => 1,
                'max_tenure_months' => 1,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SME Loan',
                'slug' => 'sme',
                'description' => 'Working capital for small and medium enterprises',
                'min_amount' => 20000,
                'max_amount' => 500000,
                'interest_rate' => 12.5,
                'processing_fee' => 1500,
                'min_tenure_months' => 6,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wedding Loan',
                'slug' => 'wedding',
                'description' => 'Fund your wedding celebrations',
                'min_amount' => 5000,
                'max_amount' => 150000,
                'interest_rate' => 10.5,
                'processing_fee' => 800,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Travel Loan',
                'slug' => 'travel',
                'description' => 'Finance holidays and travel plans',
                'min_amount' => 3000,
                'max_amount' => 80000,
                'interest_rate' => 9.5,
                'processing_fee' => 500,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vehicle Loan',
                'slug' => 'vehicle',
                'description' => 'Purchase or repair a car, motorcycle, or boda boda',
                'min_amount' => 20000,
                'max_amount' => 800000,
                'interest_rate' => 13.5,
                'processing_fee' => 2000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 48,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Loan',
                'slug' => 'medical',
                'description' => 'Cover urgent medical bills and treatment',
                'min_amount' => 1000,
                'max_amount' => 100000,
                'interest_rate' => 7.0,
                'processing_fee' => 300,
                'min_tenure_months' => 1,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Women Empowerment Loan',
                'slug' => 'women_empowerment',
                'description' => 'Discounted-rate loans for women-led businesses',
                'min_amount' => 5000,
                'max_amount' => 200000,
                'interest_rate' => 8.0,
                'processing_fee' => 500,
                'min_tenure_months' => 3,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Boda Boda Loan',
                'slug' => 'boda_boda',
                'description' => 'Buy or maintain a motorcycle for business',
                'min_amount' => 10000,
                'max_amount' => 200000,
                'interest_rate' => 12.0,
                'processing_fee' => 1000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Invoice Discounting',
                'slug' => 'invoice_discounting',
                'description' => 'Advance cash against unpaid invoices',
                'min_amount' => 20000,
                'max_amount' => 1000000,
                'interest_rate' => 11.0,
                'processing_fee' => 1500,
                'min_tenure_months' => 1,
                'max_tenure_months' => 6,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trade Finance',
                'slug' => 'trade_finance',
                'description' => 'Fund import/export and wholesale trade orders',
                'min_amount' => 50000,
                'max_amount' => 1000000,
                'interest_rate' => 13.0,
                'processing_fee' => 3000,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Construction Loan',
                'slug' => 'construction',
                'description' => 'Fund building and construction projects',
                'min_amount' => 50000,
                'max_amount' => 2000000,
                'interest_rate' => 11.5,
                'processing_fee' => 3000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'School Fees Loan',
                'slug' => 'school_fees',
                'description' => 'Cover tuition and school fee payments',
                'min_amount' => 2000,
                'max_amount' => 150000,
                'interest_rate' => 6.5,
                'processing_fee' => 300,
                'min_tenure_months' => 1,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Startup Loan',
                'slug' => 'startup',
                'description' => 'Seed capital for early-stage digital and tech businesses',
                'min_amount' => 20000,
                'max_amount' => 300000,
                'interest_rate' => 12.0,
                'processing_fee' => 1500,
                'min_tenure_months' => 6,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Livestock Loan',
                'slug' => 'livestock',
                'description' => 'Purchase or rear cattle, goats, and other livestock',
                'min_amount' => 5000,
                'max_amount' => 150000,
                'interest_rate' => 9.5,
                'processing_fee' => 500,
                'min_tenure_months' => 3,
                'max_tenure_months' => 18,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dairy Farming Loan',
                'slug' => 'dairy_farming',
                'description' => 'Finance dairy cows, equipment, and inputs',
                'min_amount' => 10000,
                'max_amount' => 200000,
                'interest_rate' => 9.0,
                'processing_fee' => 800,
                'min_tenure_months' => 6,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poultry Farming Loan',
                'slug' => 'poultry_farming',
                'description' => 'Start or scale a poultry farming venture',
                'min_amount' => 3000,
                'max_amount' => 100000,
                'interest_rate' => 9.5,
                'processing_fee' => 400,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Retail Stock Loan',
                'slug' => 'retail_stock',
                'description' => 'Restock inventory for shops and kiosks',
                'min_amount' => 3000,
                'max_amount' => 100000,
                'interest_rate' => 10.0,
                'processing_fee' => 400,
                'min_tenure_months' => 1,
                'max_tenure_months' => 6,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Import/Export Loan',
                'slug' => 'import_export',
                'description' => 'Fund cross-border trade shipments',
                'min_amount' => 50000,
                'max_amount' => 1000000,
                'interest_rate' => 13.5,
                'processing_fee' => 3000,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Solar & Green Energy Loan',
                'slug' => 'solar_energy',
                'description' => 'Finance solar panels and clean energy systems',
                'min_amount' => 5000,
                'max_amount' => 200000,
                'interest_rate' => 8.5,
                'processing_fee' => 500,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'requires_guarantor' => false,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Funeral & Bereavement Loan',
                'slug' => 'funeral',
                'description' => 'Cover funeral and bereavement expenses',
                'min_amount' => 1000,
                'max_amount' => 50000,
                'interest_rate' => 6.0,
                'processing_fee' => 200,
                'min_tenure_months' => 1,
                'max_tenure_months' => 6,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Church & Religious Institution Loan',
                'slug' => 'church',
                'description' => 'Fund church projects and religious institution needs',
                'min_amount' => 10000,
                'max_amount' => 500000,
                'interest_rate' => 10.5,
                'processing_fee' => 1000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chama/Cooperative Loan',
                'slug' => 'chama',
                'description' => 'Loans for registered savings groups and cooperatives',
                'min_amount' => 10000,
                'max_amount' => 500000,
                'interest_rate' => 9.0,
                'processing_fee' => 800,
                'min_tenure_months' => 3,
                'max_tenure_months' => 24,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Group Loan',
                'slug' => 'group_loan',
                'description' => 'Joint-liability loans for registered groups',
                'min_amount' => 5000,
                'max_amount' => 300000,
                'interest_rate' => 9.5,
                'processing_fee' => 600,
                'min_tenure_months' => 3,
                'max_tenure_months' => 18,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Payday Loan',
                'slug' => 'payday',
                'description' => 'Tiny short-term loan repaid on your next payday',
                'min_amount' => 200,
                'max_amount' => 10000,
                'interest_rate' => 5.5,
                'processing_fee' => 100,
                'min_tenure_months' => 1,
                'max_tenure_months' => 1,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Debt Consolidation Loan',
                'slug' => 'debt_consolidation',
                'description' => 'Combine multiple debts into a single repayment',
                'min_amount' => 10000,
                'max_amount' => 300000,
                'interest_rate' => 11.0,
                'processing_fee' => 1500,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'requires_guarantor' => true,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Furniture & Household Loan',
                'slug' => 'furniture',
                'description' => 'Purchase household furniture and appliances',
                'min_amount' => 3000,
                'max_amount' => 100000,
                'interest_rate' => 10.0,
                'processing_fee' => 500,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Electronics Loan',
                'slug' => 'electronics',
                'description' => 'Buy phones, laptops, and electronics on credit',
                'min_amount' => 3000,
                'max_amount' => 80000,
                'interest_rate' => 10.5,
                'processing_fee' => 400,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'requires_guarantor' => false,
                'requires_collateral' => false,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Land Purchase Loan',
                'slug' => 'land_purchase',
                'description' => 'Finance the purchase of land',
                'min_amount' => 50000,
                'max_amount' => 2000000,
                'interest_rate' => 12.5,
                'processing_fee' => 4000,
                'min_tenure_months' => 12,
                'max_tenure_months' => 60,
                'requires_guarantor' => true,
                'requires_collateral' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ], ['slug'], [
            'name',
            'description',
            'min_amount',
            'max_amount',
            'interest_rate',
            'processing_fee',
            'min_tenure_months',
            'max_tenure_months',
            'requires_guarantor',
            'requires_collateral',
            'is_active',
            'updated_at',
        ]);
    }
}